sudo: false
language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
rust:
  - 1.5.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH
script:
  - |
    travis-cargo build &&
    travis-cargo test &&
    travis-cargo bench
after_success:
  - travis-cargo --only stable coveralls --no-sudo
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=dev
